name: camera
publish_to: none
description: A Flutter plugin for controlling the camera. Supports previewing
  the camera feed, capturing images and video, and streaming image buffers to
  Dart.
repository: https://github.com/flutter/packages/tree/main/packages/camera/camera
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+camera%22
version: 0.10.5+9

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.19.3"

flutter:
  plugin:
    platforms:
      android:
        default_package: camera_android
      ios:
        default_package: camera_avfoundation
      web:
        default_package: camera_web

dependencies:
  camera_android:
    git: https://github.com/kumsumit/camera_android.git 
  camera_avfoundation: 
    git: https://github.com/kumsumit/camera_avfoundation.git
  camera_platform_interface: 
    git: https://github.com/kumsumit/camera_platform_interface.git
  camera_web: 
    git: https://github.com/kumsumit/camera_web.git
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle:
    git: https://github.com/kumsumit/flutter_plugin_android_lifecycle.git
  quiver: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  plugin_platform_interface: 
    git: https://github.com/kumsumit/plugin_platform_interface.git
  video_player: 
    git: https://github.com/kumsumit/video_player.git 

topics:
  - camera
